version: '3'

services:
  php:
    image: buzzingpixel/php7.2:latest
    container_name: php-corbomite-migrations
    environment:
      HOSTNAME: php-corbomite-migrations
    user: "1000:50"
    volumes:
      - .:/app:delegated
      - ./dev/null:/app/.git:delegated
      - ./dev/null:/app/.idea:delegated
      - ./dev/null:/app/node_modules:delegated
      - ./serverConfig/php/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini:delegated
      - ./serverConfig/php/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini:delegated
